const assert=require('assert/strict'),fs=require('fs'),path=require('path');const {pathToFileURL}=require('url');const {game}=require('./harness.cjs');
(async()=>{const THREE=await import(pathToFileURL(path.resolve(process.argv[2]))),g=await game(THREE),s=g.s,checks=[];const pass=n=>{checks.push(n);console.log('PASS',n);};
async function fresh(id='Ezreal'){s.lobbyChampion=id;await g.call('lobby','launchTraining');s.duel.nextWave=Infinity;s.duel.nextQ=Infinity;s.duel.nextW=Infinity;s.duel.nextE=Infinity;s.duel.nextR=Infinity;s.duel.nextAA=Infinity;for(const e of [...s.alliedMinions,...s.enemies.filter(e=>e.type==='minion')]){e.alive=false;e.group.visible=false;}s.player.position.set(0,0,0);s.duel.bot.group.position.set(5,0,0);s.duel.think=Infinity;s.duel.aim.copy(s.duel.bot.group.position);s.controls.cast='quick';g.tick();return s.duel;}
await fresh();g.pointer([0,0,3]);assert.equal(s.order.type,'move');g.tick(10);assert(s.player.position.z>1);g.key('KeyS');assert.equal(s.order.type,'idle');const pos=s.player.position.clone();g.tick(10);assert(s.player.position.equals(pos));pass('RMB ground movement and S/H stop preserve position');
await fresh();g.pointer([5,1,0]);assert.equal(s.order.type,'attack');g.tick();assert.equal(s.attackState,'windup');const cancels=s.cancels;g.pointer([5,1,0]);assert.equal(s.cancels,cancels);g.tick(8);assert(s.projectiles.length||s.hits>0);pass('enemy RMB starts AA; repeated clicks on the same target do not cancel windup');
await fresh();g.key('KeyA');assert(s.attackMoveArmed&&s.rangeRing.visible);g.pointer([5,0,0],0);assert.equal(s.order.type,'attackMove');assert(!s.attackMoveArmed);g.pointer([0,0,2],2,true);assert.equal(s.order.type,'attackMove');g.key('KeyX');assert.equal(s.order.type,'attackMove');pass('A-confirm, Shift-RMB and X support attack move');
await fresh();const e=await g.call('entities','createEnemy','minion',4,1,0xff0000,100,.45,'minion');s.controls.attackMoveCursor=true;assert.equal(await g.call('combat','nearestEnemyToPoint',s.duel.bot.group.position),s.duel.bot);s.controls.attackMoveCursor=false;assert.equal(await g.call('combat','nearestEnemyToPoint',s.duel.bot.group.position),e);g.key('Backquote');assert(s.targetChampionsOnly);g.pointer([4,1,1]);assert.notEqual(s.order.target,e);g.release('Backquote');assert(!s.targetChampionsOnly);pass('cursor/player attack-move priority and champion-only RMB target filtering');
await fresh();s.controls.cast='normal';g.key('KeyQ');assert(s.aim);assert(!s.abilities.cast);g.pointer([5,0,0],0);assert(!s.aim);assert.equal(s.abilities.cast.key,'Q');g.tick(6);assert(s.abilities.cooldowns.Q>g.now());pass('normal cast shows an aim indicator and reserves mana/CD only on confirmation');
await fresh();s.controls.cast='indicator';g.key('KeyW');assert(s.aim);g.release('KeyW');assert(!s.aim);assert.equal(s.abilities.cast.key,'W');g.tick(6);assert(s.abilities.shots.some(p=>p.visual==='Q')||s.abilities.cooldowns.W>g.now());pass('indicator cast fires on key release');
await fresh();g.key('KeyQ',{shiftKey:true});assert(s.aim);const mana=s.abilities.mana;g.pointer([0,0,2],2);assert(!s.aim);assert.equal(s.abilities.mana,mana);g.key('KeyQ',{shiftKey:true});g.key('Escape');assert(!s.aim&&!s.settingsOpen);pass('Shift shows indicators; RMB/Escape cancels without resource cost');
await fresh();await g.call('abilities','castSkill','Q',new THREE.Vector3(5,0,0));await g.call('abilities','castSkill','W',new THREE.Vector3(5,0,0));assert.equal(s.abilities.pending.key,'W');g.tick(7);assert(s.abilities.cooldowns.W>g.now());pass('short input buffer executes the next spell after a stationary cast');
await fresh();await g.call('abilities','castSkill','Q',new THREE.Vector3(5,0,0));await g.call('abilities','castSkill','W',new THREE.Vector3(5,0,0));g.key('KeyS');assert.equal(s.abilities.pending,null);g.tick(7);assert.equal(s.abilities.cooldowns.W,0);pass('Stop clears the queued spell');
await fresh();const mana0=s.abilities.mana;assert.equal(mana0,375);assert.equal((await g.call('abilities','abilityKit')).E.cost,70);await g.call('abilities','castSkill','F',new THREE.Vector3(10,0,0));assert(Math.abs(s.player.position.x-4)<.01);assert.equal(s.abilities.cooldowns.F-g.now(),300);await g.call('abilities','castSkill','D');assert.equal(s.abilities.cooldowns.D-g.now(),240);pass('official base mana/rank-one costs, 400-unit Flash and summoner cooldowns');
await fresh('Ashe');s.abilities.focus=4;await g.call('abilities','castSkill','Q',new THREE.Vector3(5,0,0));assert.equal(s.abilities.cooldowns.Q,g.now());assert(s.abilities.buffs.ashe>g.now());pass('zero-CD toggles do not inherit the summoner cooldown');
await fresh();s.controls.edgeScroll=false;s.cameraFocus.set(0,0,0);s.cameraLocked=false;g.key('ArrowRight');g.tick(5);g.release('ArrowRight');assert(s.cameraFocus.length()>1);g.key('Space');g.tick();assert(s.cameraFocus.equals(s.player.position));g.release('Space');g.key('KeyY');assert(s.cameraLocked);g.key('KeyY');assert(!s.cameraLocked);const offset=await g.call('camera','getCameraOffset');assert(offset.x<0&&offset.z>0);pass('diagonal camera, arrow pan, Space hold and Y toggle');
const map=g.dom.get('#minimap');map.dispatchEvent({type:'pointerdown',button:2,clientX:640,clientY:400});assert.equal(s.order.type,'move');assert(s.order.point.length()<.01);map.dispatchEvent({type:'pointerdown',button:0,clientX:800,clientY:350});assert(!s.cameraLocked);g.event({type:'pointerup',button:0});pass('diagonal minimap inverse mapping supports camera and movement');
g.key('Escape');assert(s.settingsOpen);const clock=s.duel.time;g.tick(50);assert.equal(s.duel.time,clock);g.dom.get('#castMode').value='indicator';g.dom.get('#castMode').dispatchEvent({type:'change'});assert.equal(JSON.parse(g.store.get('midDuelControls')).cast,'indicator');g.key('Escape');assert(!s.settingsOpen);pass('Escape pauses play; controls save to local storage');
await fresh();g.key('Backquote');g.key('Space');g.key('ArrowLeft');g.key('KeyA');g.event({type:'blur'});assert(!s.targetChampionsOnly&&!s.spaceHeld&&!s.attackMoveArmed);assert.equal(Object.keys(s.cameraKeys).length,0);pass('window blur releases held inputs and aim state');
await fresh();s.player.position.set(-13,0,0);await g.call('player','issueMovePoint',new THREE.Vector3(-20,0,0));let closest=Infinity;for(let i=0;i<150;i++){g.tick();closest=Math.min(closest,s.player.position.distanceTo(s.duel.blue.group.position));}assert(closest>1.7);assert(s.player.position.x< -19);pass('movement paths around tower bases instead of passing through');
let d=await fresh();d.bot.stunUntil=g.now()+2;d.nextQ=0;d.nextW=0;d.nextAA=0;g.tick(10);assert(!d.cast&&!d.botAttack);assert.equal(s.skillshotsFired,0);d.bot.stunUntil=0;d.bot.rootUntil=g.now()+2;const botPos=d.bot.group.position.clone();d.think=0;g.tick(10);assert(d.bot.group.position.equals(botPos));assert(s.skillshotsFired>0);pass('stun blocks BOT attacks/spells; root stops movement while allowing spells');
for(const key of ['Q','W','E','R']){d=await fresh();d.think=0;d.botMana=375;d['next'+key]=0;if(key==='E')d.bot.group.position.set(2,0,0);if(key==='R'){s.playerHp=30;d.bot.group.position.set(8,0,0);}g.tick(15);assert(d['next'+key]>d.time||d.cast?.key===key,'BOT '+key);assert(d.botMana<375);}pass('BOT Q/W/E/R obey cast stops, mana and independent cooldowns');
d=await fresh();const minion=await g.call('entities','createEnemy','enemy melee',1,0,0xff0000,320,.45,'minion');minion.minionClass='melee';minion.nextAttack=0;const hp=s.playerHp;d.aggressionUntil=d.time+3;g.tick(15);assert(s.playerHp<hp);pass('enemy minions retaliate after champion aggression');
d=await fresh();s.playerHp=0;d.red.hp=0;g.tick();assert(!s.player.visible);await g.call('duel','chooseDuelItem','boots');assert(s.player.visible);assert.equal(s.playerHp,100);pass('a round won while dead restores the player model for the next round');
await fresh('Vayne');s.duel.bot.group.position.set(10,0,0);const beforeMana=s.abilities.mana;await g.call('abilities','castSkill','E',s.duel.bot.group.position.clone());assert.equal(s.order.type,'castMove');assert.equal(s.abilities.mana,beforeMana);g.tick(45);assert(s.abilities.cooldowns.E>g.now());pass('out-of-range targeted spells walk into range before consuming resources');
await fresh();await g.call('abilities','castSkill','Q',new THREE.Vector3(5,0,0));g.tick();const remaining=s.abilities.cooldowns.Q-g.now(),castLeft=s.abilities.cast.until-g.now();g.key('Escape');g.tick(100);g.key('Escape');g.tick();assert(Math.abs((s.abilities.cooldowns.Q-g.now())-remaining)<.11);assert(s.abilities.cast&&Math.abs((s.abilities.cast.until-g.now())-castLeft)<.11);pass('pause preserves spell cooldowns and cast progress on resume');
// Every active slot executes with its required targeting/passive state; real Three.js intersections run.
for(const id of ['Ashe','Caitlyn','Jinx','Jhin','Ezreal','Lucian','Vayne','MissFortune','Varus','Kaisa']){for(const key of 'QWER'){d=await fresh(id);s.abilities.focus=4;d.bot.plasma=2;s.abilities.mana=1000;const result=await g.call('abilities','castSkill',key,d.bot.group.position.clone());if(id==='Vayne'&&key==='W'){assert.equal(result,false);continue;}assert.equal(result,true,id+' '+key);if(id==='Varus'&&key==='Q'){g.tick(10);await g.call('abilities','releaseCharge',d.bot.group.position.clone());}g.tick(30);assert(Number.isFinite(s.player.position.x));}}pass('all 40 champion slots resolve with targeted, charged, passive and channel rules');
fs.writeFileSync(path.join(__dirname,'../CONTROLS-TEST-RESULTS.json'),JSON.stringify({checks},null,2));})().catch(e=>{console.error(e);process.exitCode=1;});

