const assert=require('assert/strict'),fs=require('fs'),path=require('path');const {pathToFileURL}=require('url');const {game}=require('./harness.cjs');
(async()=>{
 const THREE=await import(pathToFileURL(path.resolve(process.argv[2]))),g=await game(THREE),s=g.s,checks=[];
 const pass=n=>{checks.push(n);console.log('PASS',n);};
 const launch=async(difficulty=1)=>{s.difficultyIndex=difficulty;s.lobbyMode='DUEL';s.lobbyChampion='Ezreal';await g.call('lobby','launchTraining');g.tick();return s.duel;};
 let d=await launch();assert.equal(s.mode,'DUEL');assert.equal(d.round,1);assert.equal(d.bot.group.userData.profile,'Ezreal');assert.equal(d.blue.hp,800);assert.equal(d.red.hp,800);assert.equal(s.alliedMinions.length,6);assert.equal(s.enemies.filter(e=>e.type==='minion').length,6);assert(d.red.hpBar.root.visible);
 pass('mid lane starts with equal towers, six-versus-six minions and an Ezreal bot');
 d.bot.group.position.set(6,0,0);s.player.position.set(0,0,0);d.nextQ=0;g.tick(15);assert(d.cast||s.skillshotsFired>0);const origin=d.bot.group.position.clone();if(d.cast){const dir=d.cast.dir.clone();s.player.position.z=4;g.tick(10);assert(d.shots.some(p=>p.kind==='Q'&&p.dir.equals(dir))||s.dodges>0);}assert(s.skillshotsFired>0);
 pass('entering skill range baits Q; its chosen direction stays fixed after windup');
 d=await launch();d.nextQ=Infinity;d.nextAA=Infinity;const enemy=d.bot;await g.call('combat','damageEnemy',enemy,10000,g.now(),true);g.tick();assert.equal(d.kills[0],1);g.tick(102);assert(enemy.alive);assert.equal(enemy.hp,100);
 s.playerHp=0;g.tick();assert.equal(d.kills[1],1);assert(!s.player.visible);g.tick(101);assert.equal(s.playerHp,100);assert(s.player.visible);
 pass('both champions respawn after five active seconds without ending the round');
 d=await launch();for(const a of s.alliedMinions)a.group.position.set(-10,0,0);let before=d.red.hp;await g.call('combat','damageEnemy',d.red,100,g.now(),true);assert.equal(before-d.red.hp,15);before=d.red.hp;await g.call('combat','damageEnemy',d.red,100,g.now(),true,true);assert.equal(d.red.hp,before);s.alliedMinions[0].group.position.copy(d.red.group.position);await g.call('combat','damageEnemy',d.red,100,g.now(),true);assert.equal(before-d.red.hp,100);
 pass('tower has backdoor protection, permits escorted AA and rejects spell damage');
 await g.call('combat','damageEnemy',d.red,10000,g.now(),true);g.tick();assert.equal(d.phase,'items');assert.deepEqual([...d.wins],[1,0]);const time=d.time;g.tick(50);assert.equal(d.time,time);assert.equal(await g.call('duel','chooseDuelItem','bad'),false);assert.equal(await g.call('duel','chooseDuelItem','bow'),true);assert.equal(d.round,2);assert.equal(d.phase,'play');assert.equal(d.items.length,1);assert.equal(d.botItems.length,1);assert.equal(d.red.hp,800);assert.equal(s.playerHp,100);g.tick();assert(s.ATTACK_SPEED>s.selectedChampion.as);
 pass('one tower gives one point, selection freezes play and both sides carry one item into a reset round');
 s.alliedMinions[0].group.position.copy(d.red.group.position);await g.call('combat','damageEnemy',d.red,10000,g.now(),true);g.tick();assert.equal(d.phase,'complete');assert.equal(d.wins[0],2);assert.equal(await g.call('duel','chooseDuelItem','blade'),false);
 pass('two tower wins end the match and prohibit additional equipment selection');
 d=await launch();d.blue.hp=0;g.tick();assert.equal(d.wins[1],1);await g.call('duel','chooseDuelItem','boots');d.red.hp=0;g.tick();assert.deepEqual([...d.wins],[1,1]);await g.call('duel','chooseDuelItem','armor');assert.equal(d.round,3);assert.equal(d.items.length,2);
 pass('a split score reaches round three with equal item counts');
 d=await launch();s.playerHp=100000;g.tick(1800);assert(s.enemies.length<35);assert(s.alliedMinions.length<30);assert(s.skillshotsFired>0);assert(d.botCS>0||d.phase!=='play');
 pass('long sessions continue spawning waves and fighting without unbounded dead-unit buildup');
 for(let i=0;i<3;i++){d=await launch(i);g.tick(200);assert(s.skillshotsFired>0);}pass('all three difficulties engage with reaction and aim variation');
 d=await launch();for(const a of s.alliedMinions){a.alive=false;a.group.visible=false;}for(const e of s.enemies.filter(e=>e.type==='minion'))e.group.position.set(-13,0,0);d.bot.group.position.set(-11,0,1);s.player.position.set(-20,0,0);d.blue.hp=150;d.nextWave=Infinity;d.nextQ=Infinity;g.tick(240);assert.equal(d.phase,'items');assert.equal(d.wins[1],1);pass('a bot-led wave actually destroys the defending tower through normal combat');
 for(const id of ['Ashe','Caitlyn','Jinx','Jhin','Ezreal','Lucian','Vayne','MissFortune','Varus','Kaisa']){s.lobbyMode='DUEL';s.lobbyChampion=id;await g.call('lobby','launchTraining');g.tick(80);assert.equal(s.duel.phase,'play');assert.equal(s.selectedChampion.id,id);}pass('all ten selectable champions can enter and simulate the duel');
 s.lobbyMode='CS';await g.call('lobby','launchTraining');assert.equal(s.mode,'DUEL');assert(s.duel);assert(s.player.visible);pass('retired modes cannot be reactivated');
 fs.writeFileSync(path.join(__dirname,'../DUEL-TEST-RESULTS.json'),JSON.stringify({checks},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
