const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const {pathToFileURL}=require('url');const {game}=require('./lane.test.cjs');
(async()=>{
 const THREE=await import(pathToFileURL(path.resolve(process.argv[2]))),g=await game(THREE),s=g.s,checks=[];
 const pass=n=>{checks.push(n);console.log('PASS',n);};
 const launch=async(mode='DODGE')=>{s.difficultyIndex=0;s.lobbyChampion='Ezreal';s.lobbyMode=mode;await g.call('lobby','launchTraining');s.player.position.set(0,0,0);s.modeData.time=300;const e=s.opponents?.casters[0]||s.mainDummy;e.castProfile='Ezreal';e.group.position.set(10,0,0);if(s.opponents){s.opponents.next=0;s.opponents.rotation=Infinity;}return e;};
 let e=await launch();g.tick();s.opponents.next=Infinity;s.player.position.z=1.5;
 g.tick(18);assert(!s.opponents.casts[0].warning);const origin=e.group.position.clone();g.tick(4);assert(e.group.position.equals(origin));g.tick(5);assert(!e.group.position.equals(origin));
 pass('enemy plants its feet through windup and a short release recovery, then resumes movement');
 g.tick(7);assert.equal(s.skillshotsHit,0);assert.equal(s.micro.evades,1);assert(s.micro.windows.has(e));await g.call('combat','damageEnemy',e,10,g.now(),true,false,g.now()-3);assert.equal(s.micro.returns,0);
 await g.call('combat','damageEnemy',e,10,g.now(),true,false,g.now());await g.call('combat','damageEnemy',e,10,g.now(),true,false,g.now());
 assert.equal(s.micro.returns,1);assert(s.micro.returnSeconds<2);g.tick(90);assert.equal(s.micro.evades,1);
 pass('a nearby clean dodge opens one two-second return window on its caster, without duplicate credit');
 e=await launch();g.tick();s.opponents.next=Infinity;s.player.position.z=6;g.tick(130);assert(s.dodges);assert.equal(s.micro.evades,0);
 pass('distant misses do not count as close dodge opportunities');
 e=await launch();g.tick(40);assert(s.skillshotsHit);assert.equal(s.micro.evades,0);assert.equal(s.micro.returns,0);
 pass('being hit does not award an evade or retaliation');
 e=await launch('FREE');await g.call('micro','noteEvade',e,g.now());g.tick(41);await g.call('combat','damageEnemy',e,10,g.now(),true,false,g.now());assert.equal(s.micro.returns,0);
 await g.call('micro','noteEvade',e,g.now());const other=await g.call('entities','createEnemy','OTHER',2,2);await g.call('combat','damageEnemy',other,10,g.now(),true);assert.equal(s.micro.returns,0);await g.call('combat','damageEnemy',e,0,g.now(),true);assert.equal(s.micro.returns,0);
 pass('expired windows, other targets and zero damage cannot claim retaliation');
 e.group.position.set(s.ATTACK_RANGE+s.PLAYER_RADIUS+e.radius-.1,0,0);await g.call('combat','startAttack',e,g.now());g.tick(6);g.pointer([-5,0,0]);g.tick(3);
 assert.equal(s.micro.attacks,1);assert.equal(s.micro.edgeAttacks,1);assert(s.micro.recoveryTime>0);assert(s.micro.movingRecovery>0);
 const moving=s.micro.movingRecovery;s.menuOpen=true;g.tick(10);assert.equal(s.micro.movingRecovery,moving);s.menuOpen=false;
 pass('AA range and actual movement during attack recovery are measured; menu time is excluded');
 e.microOpeningUntil=g.now()+1;await g.call('combat','damageEnemy',e,10,g.now(),true,true);assert.equal(s.micro.punishHits,1);await g.call('ui','showResult','DODGE');assert(g.dom.get('#resultObservation').textContent.includes('射程の外側'));assert(g.dom.get('#resultObservation').textContent.includes('詠唱'));
 await launch();assert.equal(s.micro.attacks,0);assert.equal(s.micro.punishHits,0);assert.equal(s.micro.windows.size,0);
 pass('opening hits appear in results and launching another session clears all metrics');
 fs.writeFileSync(path.join(__dirname,'../MICRO-TEST-RESULTS.json'),JSON.stringify({checks},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
