const assert=require('assert/strict'),fs=require('fs'),path=require('path');const {pathToFileURL}=require('url');const {game}=require('./harness.cjs');
(async()=>{const THREE=await import(pathToFileURL(path.resolve(process.argv[2]))),g=await game(THREE),s=g.s,checks=[];const pass=n=>{checks.push(n);console.log('PASS',n);};
async function fresh(){await g.call('lobby','launchTraining');g.tick();const d=s.duel;d.bot.alive=false;d.bot.group.visible=false;d.botRespawn=Infinity;s.playerHp=100000;s.player.position.set(0,0,7);return d;}
let d=await fresh();const blue=s.alliedMinions,red=s.enemies.filter(e=>e.type==='minion');assert.equal(blue.length,6);assert.equal(red.length,6);assert(blue.every(e=>e.group.position.x<d.blue.group.position.x-12));assert(red.every(e=>e.group.position.x>d.red.group.position.x+12));assert(Math.abs(d.nextWave-d.time-30)<.11);assert.equal(s.arenaBounds.maxX-s.arenaBounds.minX,78.4);pass('waves spawn beyond both towers on an extended lane, thirty seconds apart');
for(const team of [blue,red]){const melee=team.filter(e=>e.minionClass==='melee'),casters=team.filter(e=>e.minionClass==='caster');assert.equal(melee.length,3);assert.equal(casters.length,3);assert(melee.every(e=>e.group.userData.minionKind==='melee'));assert(casters.every(e=>e.group.userData.minionKind==='caster'));assert(melee[0].group.children.some(p=>p.geometry?.type==='BoxGeometry'));assert(casters[0].group.children.some(p=>p.geometry?.type==='TorusGeometry'));assert(Math.abs(melee[0].group.position.x-casters[0].group.position.x)>4.5);assert(Math.abs(melee[0].group.position.z-melee[1].group.position.z)>1.6);}pass('shield/weapon melee and hood/staff casters have separated three-unit ranks');
const first=s.alliedMinions[0],initial=first.group.position.x;g.tick(20);assert(first.group.position.x>initial);assert(first.group.position.x< -27);assert(Math.abs(first.group.position.x-initial)<3);pass('minions walk from the base at normal speed instead of snapping to the tower');
let closest=Infinity;for(let i=0;i<300;i++){g.tick();for(const e of s.alliedMinions)if(e.alive)closest=Math.min(closest,e.group.position.distanceTo(d.blue.group.position));}assert(closest>1.65);assert(s.alliedMinions.some(e=>e.alive&&e.group.position.x> -10));pass('the incoming formation walks around its own tower and reaches the central lane');
d=await fresh();for(let i=0;i<6;i++)s.alliedMinions[i].group.position.set(0,0,0);await g.call('minion-spacing','separateMinions',s.alliedMinions);let gap=Infinity;for(let i=0;i<6;i++)for(let j=i+1;j<6;j++)gap=Math.min(gap,s.alliedMinions[i].group.position.distanceTo(s.alliedMinions[j].group.position));assert(gap>1.1,'dense spacing '+gap);pass('even an initially stacked wave is separated into distinct bodies');
d=await fresh();d.nextWave=Infinity;for(const a of s.alliedMinions){a.group.position.set(-2+(a.minionClass==='caster'?-4:0),0,a.laneSlot*1.7);}for(const e of s.enemies.filter(e=>e.type==='minion'))e.group.position.set(2+(e.minionClass==='caster'?4:0),0,e.laneSlot*1.7);s.cameraFocus.set(0,0,0);g.tick(100);const enemies=s.enemies.filter(e=>e.type==='minion'&&e.alive);assert(enemies.length);assert(enemies.some(e=>e.hp<e.maxHp));for(const e of enemies){assert(Number.isFinite(e.hpBar.fill.scale.x));const q=e.group.position.clone().setY(.7).project(s.camera),picked=await g.call('entities','pickEnemy',(q.x+1)*640,(1-q.y)*400);assert.equal(picked,e,e.name+' body click');}pass('separated front/rear units fight and each enemy body can be selected accurately');
d=await fresh();for(const e of s.enemies.filter(e=>e.type==='minion')){e.alive=false;e.group.visible=false;}for(const a of s.alliedMinions)a.group.position.set(0,0,a.laneSlot*1.7+(a.minionClass==='caster'?.7:0));const hp=d.red.hp;g.tick(170);assert(d.red.hp<hp);assert.equal(d.nextWave,30.05);assert.equal(s.enemies.filter(e=>e.type==='minion'&&e.alive).length,0);pass('a cleared wave can advance and damage the enemy tower before reinforcements arrive');
d=await fresh();g.tick(595);assert.equal(s.alliedMinions.length,6);g.tick(8);assert(s.alliedMinions.length>6);const latest=s.alliedMinions.slice(-6);assert(latest.every(e=>e.group.position.x< -28));pass('the next wave arrives from the distant base, not at the contested tower');
assert.equal(s.CAMERA_PITCH_DEG,52);assert.equal(s.CAMERA_DISTANCE,29);const offset=await g.call('camera','getCameraOffset');assert(Math.abs(offset.x)>offset.z);pass('the reference camera uses a steeper diagonal lane and a lower overhead pitch');
fs.writeFileSync(path.join(__dirname,'../MINION-TEST-RESULTS.json'),JSON.stringify({checks},null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
